pipeline {
    agent {
        label 'otp'
    }
    options {
        disableConcurrentBuilds()
    }
    triggers {
        cron '''TZ=America/Chicago
        5 7 * * *'''
    }
    stages {
        stage('build') {
            steps {
                sh 'mvn clean install -DskipTests'
                dir ('surefire-reports') {
                    deleteDir()
                }
            }
        }
        stage('docker-compose-list'){
            steps {
                    sh 'docker-compose -f docker-composes/docker-compose-up.yml ps'
                }
        }
        stage('smoke-test-chrome') {
            steps {
                script {
                    sh 'mvn surefire:test -Dtest=PetroleumIndexDataVerificationTNGTest -Dbrowser=chrome'
                }
            }
        }       
    }
    post {
        always {
                    echo "Notifying build result by email to nlopez2@kopiustech.com"
                }
        success {
                    emailext body: 'The CME-Smoke Test has been successful', compressLog: true, subject: 'CME-SmokeTest - successful', to: 'nlopez2@kopiustech.com'
                }
        failure {
                    emailext body: 'The CME-Smoke Test was marked as failure', compressLog: true, subject: 'CME-SmokeTest - FAILURE', to: 'nlopez2@kopiustech.com'
                }
        unstable {
                    emailext body: 'The CME-Smoke Test was marked as unstable', compressLog: true, subject: 'CME-SmokeTest - UNSTABLE', to: 'nlopez2@kopiustech.com'
                 }
        changed {
                    emailext body: 'The CME-Smoke Test was previously failing but is now successful', compressLog: true, subject: 'CME-SmokeTest - CHANGED', to: 'nlopez2@kopiustech.com'
                }
    }
}